[tool.black]
line-length = 88
target-version = ['py38', 'py39', 'py310', 'py311']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | \.env
  | _build
  | build
  | dist
  | plantillaMaven
  | node_modules
  | static
  | uploads
  | ejerciciosEstudiantes
  | ejerciciosPropuestos
  | enunciadosEjercicios
  | tests/tmp
)/
'''